# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-actions:
    steps:
      - uses: actions/checkout@v4
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        shell: bash
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        shell: bash
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        shell: bash
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        shell: bash
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        shell: bash
        run: echo "$STRATEGY_CONTEXT"

  test-env-related-steps:
    steps:  
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        shell: bash
        run: echo "$MATRIX_CONTEXT"
    
      - name: Dump env
        env:
          ALL_ENV: ${{ toJson(env) }}
        shell: bash
        run: echo "$ALL_ENV"

      - name: Dump secrets
        env:
          ALL_SEC: ${{ toJson(secrets) }}
        shell: bash
        run: echo "$ALL_SEC"

      - name: Dump vars
        env:
          ALL_VAR: ${{ toJson(vars) }}
        shell: bash
        run: echo "$ALL_VAR"
