# This is a basic workflow to help you get started with Actions

name: callable

# Controls when the workflow will run
on:
  workflow_call:  

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        shell: bash
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        shell: bash
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        shell: bash
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        shell: bash
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        shell: bash
        run: echo "$STRATEGY_CONTEXT"

  test-env-related-steps:
    uses: .github/workflows/ci-wf.yaml@main
    strategy:
      matrix:
        environment: ["dev", "uat"]
